### ISSUE TITLE
About model

### ISSUE THREAD

**Issue by wlzxzq** [jiamingli9674/Facial_Expression_Recognition_TSLFM-CNN#1]
Thanks for your code.
I can not find your net model. Can you share me your train model?

**Comment by wlzxzq** [comment]
Also， I can not find the Dictionary Model. So can you help me.

**Comment by jiaming-cs** [comment]
Hi,

Thank you for showing interest in my project. You can download the models and try them out with this [link](https://drive.google.com/drive/folders/1FfQz4sLXtQQufha-_Iv-rIJTCDXVIIi9?usp=sharing). However, I couldn't offer you the TSLFM model since the paper has not been published. That means you can only run `video.py`. The code and models are referenced by this [repo](https://github.com/WIKI2020/FacePose_pytorch).

Thanks.
